create table expenses(
expense_id serial primary key,
AMOUNT numeric(10,2) NOT NULL,
CATEGORY VARCHAR(30) NOT NULL,
DESCRIPTION TEXT,
PAYMENT_METHOD VARCHAR(50),
EXPENSE_DATE DATE NOT NULL,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
